background_color: yellow # choose color from yellow, red, green, blue, orange, purple, black, white, gray, 
# pink, brown, cyan, teal, indigo, lime, amber, navy, olive, maroon, coral, turquoise, gold, silver, chocolate
background_color_intensity: 75 # choose number between 0 to 100